

name: deploy_front

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REACT_APP_DATABASE_URL: http://vm-26.iutrs.unistra.fr/api/
  REACT_APP_MAPBOX_TOKEN: pk.eyJ1IjoiYXNsbmRza3ZucWRvZm1uIiwiYSI6ImNreWJyN3VkZzBpNnUydm4wcnJ5MmdvYm0ifQ.YNwpI3-HgF6nMhdaRRkKBg
  

jobs:
  front:
    defaults:
      run:
        working-directory: .

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm install
    - run: npm run test
    - run: npm run build
    - name: Setup SSH connection
      uses: webfactory/ssh-agent@v0.5.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -avz -e 'ssh -p 22 -i ~/.ssh/id_rsa' ./build/ titch@${{ secrets.SSH_HOST }}:~/frontWeb/reactBuild
    - name: Rebuild deployed container
      continue-on-error: true
      run: |
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "cd ~/frontWeb && sudo docker-compose up --detach --build"
  

